# -*- coding: utf-8 -*-
"""week 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nmZUHOngbL1d6m9K05KWwL2HHjKcFYfJ
"""

import re

f = open('websiteData.txt', 'r')
data = f.read()
f.close()

pattern = '[^\w\.]\w{,8}@[a-z]*\.[a-z]*'

non_human_mails = re.findall(pattern, data)

pattern = '\w{,8}@[a-z]*\.[a-z]*'
non_human_mails = re.findall(pattern, " ".join(non_human_mails))

pattern = '[^\w]\w{1,}\.\w{1,}@[a-z]*\.[a-z]*'
human_mails = re.findall(pattern, data)

pattern = '\w{1,}\.\w{1,}@[a-z]*\.[a-z]*'
human_mails = re.findall(pattern, " ".join(human_mails))

set_human = set(human_mails)
set_non_human = set(non_human_mails)

write_data = "{ "

for i in (set_human):
  write_data += f'\"{i}\":'+'{'+f'"Occurance":{human_mails.count(i)}, "EmailType":"Human"'+'},\n'

for i in (set_non_human):
  write_data += f'\"{i}\":'+'{'+f'"Occurance":{non_human_mails.count(i)}, "EmailType":"Non-Human"'+'},\n'
write_data = write_data[:-2] + '\n}'

f= open("result.json", 'w')
f.write(write_data)
f.close()